name: CI

on:
  pull_request_target:
    types: [labeled]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Install dependencies
        run: |
          npm ci
      - name: Build package
        run: |
          npm run build
      # Manually install e2e dependencies since we don't want a package-lock
      # to mess with the our new builded package
      - name: Setup Cypress Dependencies
        run: |
          npm install -D
        working-directory: ./tests/
      - name: E2E-tests
        uses: cypress-io/github-action@v2
        with:
          # Dependencies already installed above
          install: false
          working-directory: ./tests/
        env:
          NODE_ENV: test
